[package]
name = "aksono-bin"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
aksono-api = { path = "../api" }
aksono-common = { path = "../common" }

# Tracing
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Configuration parsing
toml = { workspace = true }

# Async runtime
tokio = { workspace = true }

# Router
axum = { workspace = true }

# Argument parsing
argh = { workspace = true }

[dev-dependencies]
ruma = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

fake = { version = "3.0.1", features = ["derive"] }
assert_matches2 = "0.1.2"
assign = "1.1.1"
reqwest = { version = "0.12.12", features = ["json"] }

[lints]
workspace = true
